name: 'Testing the entire website'
on: push
jobs:
  test-the-entire-website:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repo'
        uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: 'Install repo'
        run: npm install
      - name: 'Build the site'
        run: npm run build
      - name: 'Start the server and run tests'
        run: npm run ci
