name: 'Release with semantic versioning'
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: "Install dependencies"
        run: npm install
      - name: "Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
  visual-regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repo'
        uses: actions/checkout@v2
      - name: 'Run Percy with Cypress'
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          command: npm run snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
